from .. import CONFIG

DEBUG_INPUT = CONFIG["DEBUG"]["INPUT"]
TEXTGEN_OUTPUT = CONFIG["DEBUG"]["TEXTGEN_OUTPUT"]
TEXTGEN_HISTORY = CONFIG["DEBUG"]["TEXTGEN_HISTORY"]
BULKGEN_CSV = CONFIG["DEBUG"]["BULKGEN_CSV"]
CHUNK_STATS = CONFIG["DEBUG"]["CHUNKING_STATISTICS"]
COSINE_MATRIX = CONFIG["DEBUG"]["COSINE_MATRIX"]
